export enum UsuarioErros{
    USERNAME_DUPLICADO = "USERNAME_DUPLICADO",
    CPF_DUPLICADO = "CPF_DUPLICADO",
    USUARIO_NAO_ENCONTRADO= "USUARIO_NAO_ENCONTRADO",
    CAMPO_DE_BUSCA_VAZIO = "CAMPO_DE_BUSCA_VAZIO",
}

export enum GeneroErros{
    GENERO_DUPLICADO="GENERO_DUPLICADO",
    GENERO_NAO_ENCONTRADO="GENERO_NAO_ENCONTRADO",
    CAMPO_DE_BUSCA_VAZIO = "CAMPO_DE_BUSCA_VAZIO"

}

export enum LivroErros{
    LIVRO_DUPLICADO="LIVRO_DUPLICADO",
    LIVRO_NAO_ENCONTRADO="LIVRO_NAO_ENCONTRADO",
    CAMPO_DE_BUSCA_VAZIO="CAMPO_DE_BUSCA_VAZIO"
}