export enum UsuarioErros{
    USERNAME_DUPLICADO = "USERNAME_DUPLICADO",
    CPF_DUPLICADO = "CPF_DUPLICADO",
    USUARIO_NAO_ENCONTRADO= "USUARIO_NAO_ENCONTRADO"
}

export enum GeneroErros{
    GENERO_DUPLICADO="GENERO_DUPLICADO",
    GENERO_NAO_ENCONTRADO="GENERO_NAO_ENCONTRADO"
}